# DO NOT CHANGE BELOW THIS LINE

# temporarily removed "cd onedknap && $(MAKE) $@ && cd ..&&\" due to linker issue

all dep clean indent tests::	
	cd lins  && $(MAKE) $@ && cd .. 
	cd projcoordesc && $(MAKE) $@ && cd .. 
	cd advancedcoordescent && $(MAKE) $@ && cd .. 

